// Auto-generated seed data from uploaded Google Calendar .ics exports
window.ACTIVITY_VAULT_SEED = {
  "schemaVersion": 1,
  "generatedAt": "2026-01-19T19:56:56.219Z",
  "items": [
    {
      "id": "049e242fc5e7",
      "title": "cruising",
      "summary": "",
      "type": "bar",
      "tags": [],
      "neighborhood": "West Village",
      "cost": null,
      "currency": "USD",
      "isFree": false,
      "starred": false,
      "start": "2025-10-03T01:00:00Z",
      "end": "2025-10-03T06:00:00Z",
      "allDay": false,
      "rrule": null,
      "exdate": [],
      "dateRange": null,
      "openHours": null,
      "notes": "",
      "ticketsRequired": false,
      "ticketsLink": "",
      "haveTickets": false,
      "address": "Henrietta Hudson, 438 Hudson St, New York, NY 10014, USA",
      "source": {
        "kind": "google_ics_export",
        "calendarName": "Things I want to do",
        "calendarId": "8e801f723a96cc98a85e5b0b940378972440abde3fb5ff8ba25c644adf1913e2@group.calendar.google.com",
        "uid": "0lc57nhd3pc4os031jcv3k01q3@google.com"
      },
      "layer": ""
    },
    {
      "id": "515761d72af9",
      "title": "ICE out @ Union Sq",
      "summary": "",
      "type": "community",
      "tags": [],
      "neighborhood": "Union Square",
      "cost": null,
      "currency": "USD",
      "isFree": false,
      "starred": false,
      "start": "2026-02-06T21:00:00Z",
      "end": "2026-02-06T23:00:00Z",
      "allDay": false,
      "rrule": null,
      "exdate": [],
      "dateRange": null,
      "openHours": null,
      "notes": "solidarity march",
      "ticketsRequired": false,
      "ticketsLink": "",
      "haveTickets": false,
      "address": "Union Square, New York, NY 10003, USA",
      "source": {
        "kind": "google_ics_export",
        "calendarName": "Things I want to do",
        "calendarId": "8e801f723a96cc98a85e5b0b940378972440abde3fb5ff8ba25c644adf1913e2@group.calendar.google.com",
        "uid": "5sjs6a2t0fdl52pkfd2r55d0j3@google.com"
      },
      "layer": ""
    },
    {
      "id": "d269c73a5bff",
      "title": "dyke drag",
      "summary": "",
      "type": "bar",
      "tags": [],
      "neighborhood": "Park Slope",
      "cost": null,
      "currency": "USD",
      "isFree": false,
      "starred": false,
      "start": "2025-10-15T00:00:00Z",
      "end": "2025-10-15T02:00:00Z",
      "allDay": false,
      "rrule": null,
      "exdate": [],
      "dateRange": null,
      "openHours": null,
      "notes": "",
      "ticketsRequired": false,
      "ticketsLink": "",
      "haveTickets": false,
      "address": "Ginger's Bar, 363 5th Ave, Brooklyn, NY 11215, USA",
      "source": {
        "kind": "google_ics_export",
        "calendarName": "Things I want to do",
        "calendarId": "8e801f723a96cc98a85e5b0b940378972440abde3fb5ff8ba25c644adf1913e2@group.calendar.google.com",
        "uid": "pvhcs68p2hvmnihpiqoasg2g20@google.com"
      },
      "layer": ""
    },
    {
      "id": "1ba19a6419e9",
      "title": "GhostSounds mp3 Draglesque Show",
      "summary": "",
      "type": "music",
      "tags": [],
      "neighborhood": "Sunset Park",
      "cost": null,
      "currency": "USD",
      "isFree": false,
      "starred": false,
      "start": "2025-10-04T01:00:00Z",
      "end": "2025-10-04T04:00:00Z",
      "allDay": false,
      "rrule": null,
      "exdate": [],
      "dateRange": null,
      "openHours": null,
      "notes": "",
      "ticketsRequired": false,
      "ticketsLink": "",
      "haveTickets": false,
      "address": "Sunset Stoop, 4114 5th Ave, Brooklyn, NY 11232, USA",
      "source": {
        "kind": "google_ics_export",
        "calendarName": "Things I want to do",
        "calendarId": "8e801f723a96cc98a85e5b0b940378972440abde3fb5ff8ba25c644adf1913e2@group.calendar.google.com",
        "uid": "6a1j1e1ocncquj77chhgc9esdb@google.com"
      },
      "layer": ""
    },
    {
      "id": "b2f5367c4f0b",
      "title": "We're still here performance",
      "summary": "",
      "type": "theater",
      "tags": [],
      "neighborhood": "East Williamsburg",
      "cost": null,
      "currency": "USD",
      "isFree": false,
      "starred": false,
      "start": "2025-10-02T00:00:00Z",
      "end": "2025-10-02T02:00:00Z",
      "allDay": false,
      "rrule": null,
      "exdate": [],
      "dateRange": null,
      "openHours": null,
      "notes": "",
      "ticketsRequired": false,
      "ticketsLink": "",
      "haveTickets": false,
      "address": "The Vino Theater, 274 Morgan Ave Suite 201, Brooklyn, NY 11211, USA",
      "source": {
        "kind": "google_ics_export",
        "calendarName": "Things I want to do",
        "calendarId": "8e801f723a96cc98a85e5b0b940378972440abde3fb5ff8ba25c644adf1913e2@group.calendar.google.com",
        "uid": "6ivf572sl6ehiu3ralsve4m7um@google.com"
      },
      "layer": ""
    },
    {
      "id": "e47ddee087d7",
      "title": "junk drawer",
      "summary": "",
      "type": "",
      "tags": [],
      "neighborhood": "Bedford-Stuyvesant",
      "cost": null,
      "currency": "USD",
      "isFree": false,
      "starred": false,
      "start": "2025-10-25T16:00:00Z",
      "end": "2025-10-25T22:00:00Z",
      "allDay": false,
      "rrule": null,
      "exdate": [],
      "dateRange": null,
      "openHours": null,
      "notes": "",
      "ticketsRequired": false,
      "ticketsLink": "",
      "haveTickets": false,
      "address": "616 Halsey St, Brooklyn, NY 11233, USA",
      "source": {
        "kind": "google_ics_export",
        "calendarName": "Things I want to do",
        "calendarId": "8e801f723a96cc98a85e5b0b940378972440abde3fb5ff8ba25c644adf1913e2@group.calendar.google.com",
        "uid": "n7i1h8r4itrsf2kp3dhgjrn8vk@google.com"
      },
      "layer": ""
    },
    {
      "id": "3e31eeede5c9",
      "title": "Lost Girlllll FOund at Sultan Rm",
      "summary": "",
      "type": "music",
      "tags": [],
      "neighborhood": "Bushwick",
      "cost": null,
      "currency": "USD",
      "isFree": false,
      "starred": false,
      "start": "2025-09-30T23:00:00Z",
      "end": "2025-10-01T02:00:00Z",
      "allDay": false,
      "rrule": null,
      "exdate": [],
      "dateRange": null,
      "openHours": null,
      "notes": "",
      "ticketsRequired": false,
      "ticketsLink": "",
      "haveTickets": false,
      "address": "The Sultan Room, 234 Starr St, Brooklyn, NY 11237, USA",
      "source": {
        "kind": "google_ics_export",
        "calendarName": "Things I want to do",
        "calendarId": "8e801f723a96cc98a85e5b0b940378972440abde3fb5ff8ba25c644adf1913e2@group.calendar.google.com",
        "uid": "4fjmqcvut0tishr71ipcf40jtp@google.com"
      },
      "layer": ""
    },
    {
      "id": "ee3ef03d6aed",
      "title": "gurls like gurls",
      "summary": "",
      "type": "bar",
      "tags": [],
      "neighborhood": "Bushwick",
      "cost": null,
      "currency": "USD",
      "isFree": false,
      "starred": false,
      "start": "2025-11-22T03:00:00Z",
      "end": "2025-11-22T09:00:00Z",
      "allDay": false,
      "rrule": null,
      "exdate": [],
      "dateRange": null,
      "openHours": null,
      "notes": "",
      "ticketsRequired": false,
      "ticketsLink": "",
      "haveTickets": false,
      "address": "Mood Ring, 1260 Myrtle Ave, Brooklyn, NY 11221, USA",
      "source": {
        "kind": "google_ics_export",
        "calendarName": "Things I want to do",
        "calendarId": "8e801f723a96cc98a85e5b0b940378972440abde3fb5ff8ba25c644adf1913e2@group.calendar.google.com",
        "uid": "kaqu7tqv2gusnrrr60l0c89gb8@google.com"
      },
      "layer": ""
    },
    {
      "id": "a70220ad7552",
      "title": "spooky market",
      "summary": "",
      "type": "bar",
      "tags": [],
      "neighborhood": "Park Slope",
      "cost": null,
      "currency": "USD",
      "isFree": false,
      "starred": false,
      "start": "2025-10-26T18:00:00Z",
      "end": "2025-10-26T22:00:00Z",
      "allDay": false,
      "rrule": null,
      "exdate": [],
      "dateRange": null,
      "openHours": null,
      "notes": "",
      "ticketsRequired": false,
      "ticketsLink": "",
      "haveTickets": false,
      "address": "Ginger's Bar, 363 5th Ave, Brooklyn, NY 11215, USA",
      "source": {
        "kind": "google_ics_export",
        "calendarName": "Things I want to do",
        "calendarId": "8e801f723a96cc98a85e5b0b940378972440abde3fb5ff8ba25c644adf1913e2@group.calendar.google.com",
        "uid": "urtlna56la6g0nmbl8qjejovto@google.com"
      },
      "layer": ""
    },
    {
      "id": "08391dcacf43",
      "title": "MoMA Artist Party",
      "summary": "",
      "type": "museum",
      "tags": [],
      "neighborhood": "Midtown",
      "cost": null,
      "currency": "USD",
      "isFree": false,
      "starred": false,
      "start": "2026-01-23T00:00:00Z",
      "end": "2026-01-23T03:00:00Z",
      "allDay": false,
      "rrule": null,
      "exdate": [],
      "dateRange": null,
      "openHours": null,
      "notes": "SOLD OUT :(((\nMattanaih doing Video Projections\n$15 for tickets or free for members\nmoma.org/artistparty",
      "ticketsRequired": false,
      "ticketsLink": "",
      "haveTickets": false,
      "address": "The Museum of Modern Art, 11 W 53rd St, New York, NY 10019, USA",
      "source": {
        "kind": "google_ics_export",
        "calendarName": "Things I want to do",
        "calendarId": "8e801f723a96cc98a85e5b0b940378972440abde3fb5ff8ba25c644adf1913e2@group.calendar.google.com",
        "uid": "06gcr7iipvh338jtvi8trgcoj3@google.com"
      },
      "layer": ""
    },
    {
      "id": "880d4df4a0c4",
      "title": "Strapped @ Stonewall",
      "summary": "",
      "type": "bar",
      "tags": [],
      "neighborhood": "West Village",
      "cost": null,
      "currency": "USD",
      "isFree": false,
      "starred": false,
      "start": "2025-09-30T23:30:00Z",
      "end": "2025-10-01T01:00:00Z",
      "allDay": false,
      "rrule": null,
      "exdate": [],
      "dateRange": null,
      "openHours": null,
      "notes": "",
      "ticketsRequired": false,
      "ticketsLink": "",
      "haveTickets": false,
      "address": "The Stonewall Inn, 53 Christopher St, New York, NY 10014, USA",
      "source": {
        "kind": "google_ics_export",
        "calendarName": "Things I want to do",
        "calendarId": "8e801f723a96cc98a85e5b0b940378972440abde3fb5ff8ba25c644adf1913e2@group.calendar.google.com",
        "uid": "1hhcj7hn7fibb495mp5btnvsa2@google.com"
      },
      "layer": ""
    },
    {
      "id": "1a9ed5cf55a8",
      "title": "singles night",
      "summary": "",
      "type": "bar",
      "tags": [],
      "neighborhood": "Bushwick",
      "cost": null,
      "currency": "USD",
      "isFree": false,
      "starred": false,
      "start": "2025-10-03T22:00:00Z",
      "end": "2025-10-04T00:00:00Z",
      "allDay": false,
      "rrule": null,
      "exdate": [],
      "dateRange": null,
      "openHours": null,
      "notes": "",
      "ticketsRequired": false,
      "ticketsLink": "",
      "haveTickets": false,
      "address": "The Bush, 333 Troutman St Store 4, Brooklyn, NY 11237, USA",
      "source": {
        "kind": "google_ics_export",
        "calendarName": "Things I want to do",
        "calendarId": "8e801f723a96cc98a85e5b0b940378972440abde3fb5ff8ba25c644adf1913e2@group.calendar.google.com",
        "uid": "i280pna5ud7necv5rjsspup430@google.com"
      },
      "layer": ""
    },
    {
      "id": "b8a066366421",
      "title": "queer concious",
      "summary": "",
      "type": "community",
      "tags": [],
      "neighborhood": "Bushwick",
      "cost": null,
      "currency": "USD",
      "isFree": false,
      "starred": false,
      "start": "2025-10-05T20:00:00Z",
      "end": "2025-10-05T23:00:00Z",
      "allDay": false,
      "rrule": null,
      "exdate": [],
      "dateRange": null,
      "openHours": null,
      "notes": "",
      "ticketsRequired": false,
      "ticketsLink": "",
      "haveTickets": false,
      "address": "BOYFRIEND co-op, 1157 Myrtle Ave, Brooklyn, NY 11206, USA",
      "source": {
        "kind": "google_ics_export",
        "calendarName": "Things I want to do",
        "calendarId": "8e801f723a96cc98a85e5b0b940378972440abde3fb5ff8ba25c644adf1913e2@group.calendar.google.com",
        "uid": "2lv0b6tb4he8d99fsp5a3m0tbm@google.com"
      },
      "layer": ""
    },
    {
      "id": "93b2d1464606",
      "title": "3 $ bill- halloween",
      "summary": "",
      "type": "music",
      "tags": [],
      "neighborhood": "East Williamsburg",
      "cost": null,
      "currency": "USD",
      "isFree": false,
      "starred": false,
      "start": "2025-10-26T02:00:00Z",
      "end": "2025-10-26T06:00:00Z",
      "allDay": false,
      "rrule": null,
      "exdate": [],
      "dateRange": null,
      "openHours": null,
      "notes": "",
      "ticketsRequired": false,
      "ticketsLink": "",
      "haveTickets": false,
      "address": "3 Dollar Bill, 260 Meserole St, Brooklyn, NY 11206, USA",
      "source": {
        "kind": "google_ics_export",
        "calendarName": "Things I want to do",
        "calendarId": "8e801f723a96cc98a85e5b0b940378972440abde3fb5ff8ba25c644adf1913e2@group.calendar.google.com",
        "uid": "5j059m47qapqc64e5m9lo5juic@google.com"
      },
      "layer": ""
    },
    {
      "id": "7385517cdb14",
      "title": "nyc gladiators",
      "summary": "",
      "type": "museum",
      "tags": [],
      "neighborhood": "Upper East Side",
      "cost": null,
      "currency": "USD",
      "isFree": false,
      "starred": false,
      "start": "2025-12-13T19:00:00Z",
      "end": "2025-12-13T21:00:00Z",
      "allDay": false,
      "rrule": null,
      "exdate": [],
      "dateRange": null,
      "openHours": null,
      "notes": "central park, sw corner of the met",
      "ticketsRequired": false,
      "ticketsLink": "",
      "haveTickets": false,
      "address": "The Metropolitan Museum of Art, 1000 5th Ave, New York, NY 10028, USA",
      "source": {
        "kind": "google_ics_export",
        "calendarName": "Things I want to do",
        "calendarId": "8e801f723a96cc98a85e5b0b940378972440abde3fb5ff8ba25c644adf1913e2@group.calendar.google.com",
        "uid": "03gur57uflg6v31sqc9fm88qgc@google.com"
      },
      "layer": ""
    },
    {
      "id": "7b3d11dee4e1",
      "title": "Creative Coding NYC",
      "summary": "",
      "type": "",
      "tags": [],
      "neighborhood": "Chelsea",
      "cost": null,
      "currency": "USD",
      "isFree": false,
      "starred": false,
      "start": "2026-01-20T23:00:00Z",
      "end": "2026-01-21T01:00:00Z",
      "allDay": false,
      "rrule": null,
      "exdate": [],
      "dateRange": null,
      "openHours": null,
      "notes": "",
      "ticketsRequired": false,
      "ticketsLink": "",
      "haveTickets": false,
      "address": "Pier 57, 25 11th Ave, New York, NY 10011, USA",
      "source": {
        "kind": "google_ics_export",
        "calendarName": "Things I want to do",
        "calendarId": "8e801f723a96cc98a85e5b0b940378972440abde3fb5ff8ba25c644adf1913e2@group.calendar.google.com",
        "uid": "7ocu3rd8jfokiir4jdqlddqqe2@google.com"
      },
      "layer": ""
    },
    {
      "id": "b4c5233b1c35",
      "title": "Ice Out For Good",
      "summary": "",
      "type": "community",
      "tags": [],
      "neighborhood": "Union Square",
      "cost": null,
      "currency": "USD",
      "isFree": false,
      "starred": false,
      "start": "2026-01-23T21:00:00Z",
      "end": "2026-01-23T23:30:00Z",
      "allDay": false,
      "rrule": null,
      "exdate": [],
      "dateRange": null,
      "openHours": null,
      "notes": "Solidarity March",
      "ticketsRequired": false,
      "ticketsLink": "",
      "haveTickets": false,
      "address": "Union Square, New York, NY 10003, USA",
      "source": {
        "kind": "google_ics_export",
        "calendarName": "Things I want to do",
        "calendarId": "8e801f723a96cc98a85e5b0b940378972440abde3fb5ff8ba25c644adf1913e2@group.calendar.google.com",
        "uid": "6a21ls0ejmco1b9chfeopekiq7@google.com"
      },
      "layer": ""
    },
    {
      "id": "453532080c58",
      "title": "Rack shack",
      "summary": "",
      "type": "",
      "tags": [],
      "neighborhood": "East Williamsburg",
      "cost": null,
      "currency": "USD",
      "isFree": false,
      "starred": false,
      "start": "2025-10-02T23:00:00Z",
      "end": "2025-10-03T00:00:00Z",
      "allDay": false,
      "rrule": null,
      "exdate": [],
      "dateRange": null,
      "openHours": null,
      "notes": "",
      "ticketsRequired": false,
      "ticketsLink": "",
      "haveTickets": false,
      "address": "The Rack Shack, 17 Thames St, Brooklyn, NY 11206, USA",
      "source": {
        "kind": "google_ics_export",
        "calendarName": "Things I want to do",
        "calendarId": "8e801f723a96cc98a85e5b0b940378972440abde3fb5ff8ba25c644adf1913e2@group.calendar.google.com",
        "uid": "50uivi8pdh1s6sjflkfdtr4eog@google.com"
      },
      "layer": ""
    },
    {
      "id": "b60869ad8929",
      "title": "turnstile jumping competition at morgan ave",
      "summary": "",
      "type": "",
      "tags": [],
      "neighborhood": "East Williamsburg",
      "cost": null,
      "currency": "USD",
      "isFree": false,
      "starred": false,
      "start": "2026-02-07T19:00:00Z",
      "end": "2026-02-07T21:30:00Z",
      "allDay": false,
      "rrule": null,
      "exdate": [],
      "dateRange": null,
      "openHours": null,
      "notes": "",
      "ticketsRequired": false,
      "ticketsLink": "",
      "haveTickets": false,
      "address": "Morgan Ave Station (L), Brooklyn, NY 11237, USA",
      "source": {
        "kind": "google_ics_export",
        "calendarName": "Things I want to do",
        "calendarId": "8e801f723a96cc98a85e5b0b940378972440abde3fb5ff8ba25c644adf1913e2@group.calendar.google.com",
        "uid": "spoart441f098n8r7qamo4f4rs@google.com"
      },
      "layer": ""
    },
    {
      "id": "e3d7ee80a11a",
      "title": "the woods",
      "summary": "",
      "type": "bar",
      "tags": [],
      "neighborhood": "Williamsburg",
      "cost": null,
      "currency": "USD",
      "isFree": false,
      "starred": false,
      "start": "2025-10-01T22:00:00",
      "end": "2025-10-02T04:00:00",
      "allDay": false,
      "rrule": "FREQ=WEEKLY;UNTIL=20251224T045959Z;BYDAY=WE",
      "exdate": [
        "2025-12-03T22:00:00"
      ],
      "dateRange": null,
      "openHours": null,
      "notes": "",
      "ticketsRequired": false,
      "ticketsLink": "",
      "haveTickets": false,
      "address": "The Woods, 48 S 4th St, Brooklyn, NY 11249, USA",
      "source": {
        "kind": "google_ics_export",
        "calendarName": "Things I want to do",
        "calendarId": "8e801f723a96cc98a85e5b0b940378972440abde3fb5ff8ba25c644adf1913e2@group.calendar.google.com",
        "uid": "61mpid0fc2jffp2k2sl6fje088@google.com"
      },
      "layer": ""
    },
    {
      "id": "5e501973622a",
      "title": "halloween dog parade",
      "summary": "",
      "type": "outdoors",
      "tags": [],
      "neighborhood": "East Village",
      "cost": null,
      "currency": "USD",
      "isFree": false,
      "starred": false,
      "start": "2025-10-19",
      "end": "2025-10-20",
      "allDay": true,
      "rrule": null,
      "exdate": [],
      "dateRange": null,
      "openHours": null,
      "notes": "",
      "ticketsRequired": false,
      "ticketsLink": "",
      "haveTickets": false,
      "address": "Tompkins Square Park, E 10th St, New York, NY 10009, USA",
      "source": {
        "kind": "google_ics_export",
        "calendarName": "Things I want to do",
        "calendarId": "8e801f723a96cc98a85e5b0b940378972440abde3fb5ff8ba25c644adf1913e2@group.calendar.google.com",
        "uid": "kuj4bqct3u7qok59d4shdkk0ko@google.com"
      },
      "layer": ""
    },
    {
      "id": "e10b4894cf09",
      "title": "The Whitney",
      "summary": "",
      "type": "museum",
      "tags": [
        "layer",
        "free"
      ],
      "neighborhood": "Meatpacking District",
      "cost": 0,
      "currency": "USD",
      "isFree": true,
      "starred": false,
      "start": "2026-01-10T10:30:00",
      "end": "2026-01-10T18:00:00",
      "allDay": false,
      "rrule": "FREQ=MONTHLY;BYDAY=2SU",
      "exdate": [],
      "dateRange": null,
      "openHours": null,
      "notes": "",
      "ticketsRequired": false,
      "ticketsLink": "",
      "haveTickets": false,
      "address": "Whitney Museum of American Art, 99 Gansevoort St, New York, NY 10014, USA",
      "source": {
        "kind": "google_ics_export",
        "calendarName": "Museum Free Days",
        "calendarId": "ba23a5908d03b0a01cb8d8e365a777ec1a35205b5ef189ace7fd7cdb18129407@group.calendar.google.com",
        "uid": "18ccrbh9amfh9tgi9e70st1mgg@google.com"
      },
      "layer": "museumFreeTimes"
    },
    {
      "id": "922d2eebf9fe",
      "title": "Poster House",
      "summary": "",
      "type": "museum",
      "tags": [
        "layer",
        "free"
      ],
      "neighborhood": "Chelsea",
      "cost": 0,
      "currency": "USD",
      "isFree": true,
      "starred": false,
      "start": "2026-01-18T10:00:00",
      "end": "2026-01-18T18:00:00",
      "allDay": false,
      "rrule": "FREQ=MONTHLY;BYDAY=3SU",
      "exdate": [],
      "dateRange": null,
      "openHours": null,
      "notes": "",
      "ticketsRequired": false,
      "ticketsLink": "",
      "haveTickets": false,
      "address": "Poster House, 119 W 23rd St, New York, NY 10011, USA",
      "source": {
        "kind": "google_ics_export",
        "calendarName": "Museum Free Days",
        "calendarId": "ba23a5908d03b0a01cb8d8e365a777ec1a35205b5ef189ace7fd7cdb18129407@group.calendar.google.com",
        "uid": "24o7dn0avmju79990v4ijqd1h5@google.com"
      },
      "layer": "museumFreeTimes"
    },
    {
      "id": "fa4aeefa514b",
      "title": "9/11 Museum",
      "summary": "",
      "type": "museum",
      "tags": [
        "layer",
        "free"
      ],
      "neighborhood": "Financial District",
      "cost": 0,
      "currency": "USD",
      "isFree": true,
      "starred": false,
      "start": "2026-01-04T09:00:00",
      "end": "2026-01-04T19:00:00",
      "allDay": false,
      "rrule": "FREQ=MONTHLY;BYDAY=1SU",
      "exdate": [],
      "dateRange": null,
      "openHours": null,
      "notes": "",
      "ticketsRequired": false,
      "ticketsLink": "",
      "haveTickets": false,
      "address": "9/11 Memorial & Museum, 180 Greenwich St, New York, NY 10007, USA",
      "source": {
        "kind": "google_ics_export",
        "calendarName": "Museum Free Days",
        "calendarId": "ba23a5908d03b0a01cb8d8e365a777ec1a35205b5ef189ace7fd7cdb18129407@group.calendar.google.com",
        "uid": "3jbcke24mvocl3rtnf6aj9sscl@google.com"
      },
      "layer": "museumFreeTimes"
    },
    {
      "id": "df0d36198ea0",
      "title": "Museum of the City of NYC",
      "summary": "",
      "type": "museum",
      "tags": [
        "layer",
        "free"
      ],
      "neighborhood": "East Harlem",
      "cost": 0,
      "currency": "USD",
      "isFree": true,
      "starred": false,
      "start": "2026-01-14T10:00:00",
      "end": "2026-01-14T17:00:00",
      "allDay": false,
      "rrule": "FREQ=WEEKLY;BYDAY=WE",
      "exdate": [],
      "dateRange": null,
      "openHours": null,
      "notes": "",
      "ticketsRequired": false,
      "ticketsLink": "",
      "haveTickets": false,
      "address": "Museum of the City of New York, 1220 5th Ave, New York, NY 10029, USA",
      "source": {
        "kind": "google_ics_export",
        "calendarName": "Museum Free Days",
        "calendarId": "ba23a5908d03b0a01cb8d8e365a777ec1a35205b5ef189ace7fd7cdb18129407@group.calendar.google.com",
        "uid": "1b10vqgqmm6hkmr62t3moaq88e@google.com"
      },
      "layer": "museumFreeTimes"
    },
    {
      "id": "ead96735ff13",
      "title": "Poster House",
      "summary": "",
      "type": "museum",
      "tags": [
        "layer",
        "free"
      ],
      "neighborhood": "Chelsea",
      "cost": 0,
      "currency": "USD",
      "isFree": true,
      "starred": false,
      "start": "2026-01-16T10:00:00",
      "end": "2026-01-16T21:00:00",
      "allDay": false,
      "rrule": "FREQ=WEEKLY;BYDAY=FR",
      "exdate": [],
      "dateRange": null,
      "openHours": null,
      "notes": "",
      "ticketsRequired": false,
      "ticketsLink": "",
      "haveTickets": false,
      "address": "Poster House, 119 W 23rd St, New York, NY 10011, USA",
      "source": {
        "kind": "google_ics_export",
        "calendarName": "Museum Free Days",
        "calendarId": "ba23a5908d03b0a01cb8d8e365a777ec1a35205b5ef189ace7fd7cdb18129407@group.calendar.google.com",
        "uid": "74gbf8kb87cn3a06nqukl2em4g@google.com"
      },
      "layer": "museumFreeTimes"
    },
    {
      "id": "a96cd31fe2e8",
      "title": "Cooper Hewitt",
      "summary": "",
      "type": "museum",
      "tags": [
        "layer",
        "free"
      ],
      "neighborhood": "Upper East Side",
      "cost": 0,
      "currency": "USD",
      "isFree": true,
      "starred": false,
      "start": "2026-01-19T17:00:00",
      "end": "2026-01-19T18:00:00",
      "allDay": false,
      "rrule": "FREQ=DAILY",
      "exdate": [],
      "dateRange": null,
      "openHours": null,
      "notes": "Pay what you wish",
      "ticketsRequired": false,
      "ticketsLink": "",
      "haveTickets": false,
      "address": "Cooper Hewitt, Smithsonian Design Museum, 2 E 91st St, New York, NY 10128, USA",
      "source": {
        "kind": "google_ics_export",
        "calendarName": "Museum Free Days",
        "calendarId": "ba23a5908d03b0a01cb8d8e365a777ec1a35205b5ef189ace7fd7cdb18129407@group.calendar.google.com",
        "uid": "78ld7bpv1tupcdhirfr9703ktb@google.com"
      },
      "layer": "museumFreeTimes"
    },
    {
      "id": "3b2ec583cf99",
      "title": "MoMA",
      "summary": "",
      "type": "museum",
      "tags": [
        "layer",
        "free"
      ],
      "neighborhood": "Midtown",
      "cost": 0,
      "currency": "USD",
      "isFree": true,
      "starred": false,
      "start": "2026-01-16T17:30:00",
      "end": "2026-01-16T20:30:00",
      "allDay": false,
      "rrule": "FREQ=WEEKLY;BYDAY=FR",
      "exdate": [],
      "dateRange": null,
      "openHours": null,
      "notes": "Advanced Ticket",
      "ticketsRequired": false,
      "ticketsLink": "",
      "haveTickets": false,
      "address": "The Museum of Modern Art, 11 W 53rd St, New York, NY 10019, USA",
      "source": {
        "kind": "google_ics_export",
        "calendarName": "Museum Free Days",
        "calendarId": "ba23a5908d03b0a01cb8d8e365a777ec1a35205b5ef189ace7fd7cdb18129407@group.calendar.google.com",
        "uid": "1ndl98ontfo1hnnuc8djb53jev@google.com"
      },
      "layer": "museumFreeTimes"
    },
    {
      "id": "fecef92484dc",
      "title": "The Whitney",
      "summary": "",
      "type": "museum",
      "tags": [
        "layer",
        "free"
      ],
      "neighborhood": "Meatpacking District",
      "cost": 0,
      "currency": "USD",
      "isFree": true,
      "starred": false,
      "start": "2026-01-16T17:00:00",
      "end": "2026-01-16T22:00:00",
      "allDay": false,
      "rrule": "FREQ=WEEKLY;BYDAY=FR",
      "exdate": [],
      "dateRange": null,
      "openHours": null,
      "notes": "",
      "ticketsRequired": false,
      "ticketsLink": "",
      "haveTickets": false,
      "address": "Whitney Museum of American Art, 99 Gansevoort St, New York, NY 10014, USA",
      "source": {
        "kind": "google_ics_export",
        "calendarName": "Museum Free Days",
        "calendarId": "ba23a5908d03b0a01cb8d8e365a777ec1a35205b5ef189ace7fd7cdb18129407@group.calendar.google.com",
        "uid": "1oj0vdetp3c9p1vvg4i8dtv8mj@google.com"
      },
      "layer": "museumFreeTimes"
    },
    {
      "id": "662fdca3818b",
      "title": "Morgan Library",
      "summary": "",
      "type": "museum",
      "tags": [
        "layer",
        "free"
      ],
      "neighborhood": "Murray Hill",
      "cost": 0,
      "currency": "USD",
      "isFree": true,
      "starred": false,
      "start": "2026-01-16T22:00:00Z",
      "end": "2026-01-17T01:00:00Z",
      "allDay": false,
      "rrule": null,
      "exdate": [],
      "dateRange": null,
      "openHours": null,
      "notes": "requires advanced ticket",
      "ticketsRequired": false,
      "ticketsLink": "",
      "haveTickets": false,
      "address": "The Morgan Library & Museum, 225 Madison Ave, New York, NY 10016, USA",
      "source": {
        "kind": "google_ics_export",
        "calendarName": "Museum Free Days",
        "calendarId": "ba23a5908d03b0a01cb8d8e365a777ec1a35205b5ef189ace7fd7cdb18129407@group.calendar.google.com",
        "uid": "0likh64q8q5eu0rf6tua558jvv@google.com"
      },
      "layer": "museumFreeTimes"
    }
  ]
};
